name: Get new data from database every week
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 3"
jobs:
  get-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Run
        run: |
          pip3 install pandas
          pip3 install sqlalchemy
          pip3 install psycopg2
          pip3 install python-dotenv
          python3 ./query_db.py
        env:
            NYCDB_DATABASE: ${{ secrets.NYCDB_DATABASE }}
      - name: Commit updates
        uses: EndBug/add-and-commit@v4
        with:
          author_name: bot
          author_email: bot@example.com
          message: "Update SQL"
          add: "*.csv"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
